language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
after_success:
  - npm install -g codecov semantic-release
  - codecov
  - semantic-release pre && npm publish && semantic-release post
branches:
  only:
    - master
    - /^greenkeeper/.*$/
