language: node_js
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
after_success: if [[ `node -v` == v10* ]]; then npx codecov; fi
branches:
  only:
    - master
    - /^greenkeeper/.*$/
