language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '6'
script:
  - npm run lint
  - node node_modules/.bin/prettier -l "*.{js,json,md}"
  - npm run test
after_success:
  - if [[ `npm -v` > 4* ]]; then npx codecov; fi
  - npm install -g semantic-release@11
  - semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
