language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - if [[ `npm -v` > 4* ]]; then npx codecov; fi
  - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
